basic_app/urls.py
from django.urls import path
from basic_app import views


app_name = "basic_app"

urlpatterns = [
    path("", views.HomePage.as_view(), name='home'),
    path("user/kyc/", views.upload_kyc, name="kyc"),
    path("user/deposit/", views.upload_receipt, name="user-deposit"),
    path('user/dashboard/', views.user_dashboard_view, name='user-dashboard'),
    path('user/schema/logs/', views.user_schemaLogs_view, name='user-schema-logs'),
    path('user/deposit/logs/', views.user_depositLogs_view, name='user-deposit-logs'),
    path('user/ranking/', views.user_rankingBadge_view, name='user-ranking'),
    path('user/referral/', views.user_referral_view, name='user-referral'),
    path('user/schemas/', views.user_schemas_view, name='user-schemas'),
    path('user/transactions/', views.user_transactions_view, name='user-transactions'),
    path('user/kyc-verification/', views.user_verifyKyc_view, name='user-verify-kyc'),
    path('user/receipt-confirmation/', views.user_verifyReceipt_view, name='user-verify-receipt'),
    path('user/withdraw/logs/', views.user_withdrawLogs_view, name='user-withdraw-logs'),
    path('user/withdraw/', views.user_withdraw_view, name='user-withdraw'),
    path('user/dashboard-first/', views.UserDashboardFirst.as_view(), name='user-dashboard-first'),
    path('user/dashboard/active/', views.user_active_view, name='user-active'),
    path('user/dashboard/commission-fee/', views.user_commission_view, name='user-commission-fee'),
    path('user/dashboard/conversion-fee/', views.user_conversion_view, name='user-conversion-fee'),
    path('user/dashboard/top-up-fee/', views.user_topup_view, name='user-topup'),
    path('user/dashboard/pending/', views.user_pending_view, name='user-pending'),

    path("schema/", views.SchemaPage.as_view(), name='schema'),
    path("rankings/", views.RankingsPage.as_view(), name='rankings'),
    path("how-it-works/", views.HowItWorks.as_view(), name="how-it-works"),
    path("about-us/", views.AboutUs.as_view(), name='about-us'),
    path("blog/", views.Blog.as_view(), name='blog'),
    path("contact-us/", views.contact_form, name='contact'),
    path("contact-us/success", views.ContactSuccess.as_view(), name='contact-success'),
    path("privacy-policy/", views.PrivacyPolicy.as_view(), name='privacy'),
    path("faq/", views.FAQ.as_view(), name='faq'),
    path("terms-conditions/", views.TermsAndConditions.as_view(), name='terms'),
    path("blog/1/", views.BlogFirst.as_view(), name='blog-first'),
    path("blog/2/", views.BlogSecond.as_view(), name='blog-second'),
    path("register/", views.SignUpView.as_view(), name='register'),
    path("login/", views.login_request, name="login"),
    path('logout/', views.logout_request, name='logout'),

]


from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

firstcp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basic_app.urls', namespace='basic_app')),
]

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'images/icon.png' %}" type="image/x-icon"/>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/carousel.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}"/>
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.8/datatables.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/laravel-notify.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>

    <style>
        * { font-weight: 400; font-size: 0.95rem; color: rgb(128, 124, 124); font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif ;}
        .site-head-tag { margin: 0; padding: 0; }
        .site-nice-select { color: rgb(128, 124, 124); font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;}
        .messages ul li { color: red; }
        .box-input input {
            width: 100%;
            height: 50px;
            border-radius: 4px;
            text-indent: 15px;
            background: #ffffff;
            transition: 0.3s;
            border: 1px solid transparent;
            position: relative;
            border: 1px solid #cdd4e7;
        }

    </style>

    <title>AIM CAPITAL MARKET- Login</title>
</head>

<body class="dark-theme">
    <script>
        var notify = {
            timeout: "5000",
        }
    </script>


    <!-- Login Section -->
    <section class="section-style site-auth">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-5 col-lg-8 col-md-12">
                    <div class="auth-content">
                        <div class="logo">
                            <a class="navbar-brand" href="{% url 'basic_app:home' %}"><img src="{% static 'images/icon.png' %}" alt=""/></a>
                        </div>
                        <div class="title">
                            <h2> 👋 Welcome Back!</h2>
                            <p>Sign in to continue with Aim Capital Market</p>
                        </div>

                        {% if messages %}
                        <div class="messages">
                            <ul class="errorlist">
                                {% for message in messages %}
                                    <li>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                        {% endif %}


                        <div class="site-auth-form">
                            <form method="POST" class="row">
                                {% csrf_token %}
                                <div class="single-field box-input">
                                    <label class="box-label" for="username">Username</label>
                                    {{ login.username }}
                                </div>
                                <div class="single-field box-input">
                                    <label class="box-label" for="password">Password</label>
                                    {{ login.password }}

                                </div>


                                <div class="single-field">
                                    <input
                                        class="form-check-input check-input"
                                        type="checkbox"
                                        name="remember"
                                        id="flexCheckDefault"
                                    />
                                    <label class="form-check-label" for="flexCheckDefault">
                                        Remember me
                                    </label>

                                                                            <span class="forget-pass-text"><a
                                                href="https://valortechtrade.com/forgot-password">Forget Password</a></span>
                                                                    </div>
                                <button type="submit" class="site-btn grad-btn w-100">
                                    Account Login
                                </button>
                            </form>
                            <div class="singnup-text">
                                <p>
                                    Don&#039;t have an account?
                                    <a href="{% url 'basic_app:register' %}">Signup for free</a> <br>
                                    <a href="{% url 'basic_app:home' %}">Home</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Login Section End -->

    <script src="{% static 'javascript/jquery.min.js' %}"></script>
    <script src="{% static 'javascript/jquery-migrate.js' %}"></script>

    <script src="{% static 'javascript/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'javascript/scrollUp.min.js' %}"></script>

    <script src="{% static 'javascript/owl.carousel.min.js' %}"></script>
    <script src="{% static 'javascript/waypoints.min.js' %}"></script>
    <script src="{% static 'javascript/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'javascript/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'javascript/lucide.min.js' %}"></script>
    <script src="{% static 'javascript/magnific-popup.min.js' %}"></script>
    <script src="{% static 'javascript/aos.js' %}"></script>
    <script src="{% static 'javascript/datatables.min.js' %}" type="text/javascript" charset="utf8"></script>
    <script src="{% static 'javascript/frontend.main.js' %}"></script>
    <script src="{% static 'javascript/cookie.js' %}"></script>
    <script src="{% static 'javascript/custom.js' %}"></script>



    <script>
        (function ($) {
            'use strict';
            // To top
            $.scrollUp({
                scrollText: '<i class="fas fa-caret-up"></i>',
                easingType: 'linear',
                scrollSpeed: 500,
                animation: 'fade'
            });
        })(jQuery);
    </script>

<script type="text/javascript" src="{% static 'javascript/notify.js' %}"></script>        <script>
        $('#countrySelect').on('change', function (e) {
            "use strict";
            e.preventDefault();
            var country = $(this).val();
            $('#dial-code').html(country.split(":")[1])
        })
</script>

<script>
    // Function to hide the message after 5 seconds (5000 milliseconds)
    setTimeout(function() {
        var messages = document.querySelector(".messages");
        if (messages) {
            messages.style.display = "none";
        }
    }, 4000); // Adjust the time (in milliseconds) as needed
</script>

<!--Start of Tawk.to Script-->
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/675866e8af5bfec1dbd9e469/1ieol3vh8';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->

</body>
</html>